(library
 (name lunarpc_generator)
 (public_name lunarpc-generator)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Lunarpc_stdlib)
 (libraries base base_quickcheck lunarpc_stdlib sexplib0)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess no_preprocessing))
