(library
 (name keyval_rpc)
 (package lunarpc-tests)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Lunarpc
  -open
  Lunarpc_discovery
  -open
  Lunarpc_stdlib)
 (libraries keyval lunarpc lunarpc_discovery lunarpc_stdlib)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess no_preprocessing))
